//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.articulo_grupo = new HashSet<articulo_grupo>();
        }
    
        public int idArticulo { get; set; }
        public string Nombre { get; set; }
        public string Autores { get; set; }
        public Nullable<int> Volumen { get; set; }
        public Nullable<int> PagInicio { get; set; }
        public Nullable<int> PagFinal { get; set; }
        public string Revista { get; set; }
        public string ISSN { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<int> Archivo { get; set; }
        public Nullable<int> TipoArticulo { get; set; }
    
        public virtual archivo archivo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo_grupo> articulo_grupo { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual tipoarticulo tipoarticulo1 { get; set; }
    }
}
