//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class concentrado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public concentrado()
        {
            this.concentrado_grupos = new HashSet<concentrado_grupos>();
        }
    
        public int idConcentrado { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Fecha { get; set; }
        public string Autores { get; set; }
        public Nullable<int> TipoConcentrado { get; set; }
        public Nullable<int> IdItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concentrado_grupos> concentrado_grupos { get; set; }
    }
}
