//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos()
        {
            this.proyecto_grupo = new HashSet<proyecto_grupo>();
            this.proyecto_usuario = new HashSet<proyecto_usuario>();
        }
    
        public int idProyecto { get; set; }
        [DisplayName("Nombre del Proyecto")]
        [Required]
        public string nombre { get; set; }
        public string Financiamiento { get; set; }
        [Required]
        [DisplayName("Fecha de Inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode= true)]
        public Nullable<System.DateTime> FechaInicio { get; set; }
        [Required]
        [DisplayName("Fecha Final")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode= true)]
        public Nullable<System.DateTime> FechaFinal { get; set; }
        [Required]      
        public Nullable<int> Usuario { get; set; }
        public Nullable<int> Archivo { get; set; }
        public string Clave { get; set; }
    
        public virtual archivo archivo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyecto_grupo> proyecto_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyecto_usuario> proyecto_usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
