//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tesis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tesis()
        {
            this.tesis_grupo = new HashSet<tesis_grupo>();
        }
    
        public int idtesis { get; set; }
        public string titulo { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> archivo { get; set; }
        public string director { get; set; }
        public Nullable<int> asesor { get; set; }
        public string codirector { get; set; }
        public string jurado { get; set; }
        public Nullable<int> autor { get; set; }
    
        public virtual archivo archivo1 { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tesis_grupo> tesis_grupo { get; set; }
        public virtual usuario usuario21 { get; set; }
    }
}
