//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.articulo = new HashSet<articulo>();
            this.articulo_usuario = new HashSet<articulo_usuario>();
            this.capitulo_usuario = new HashSet<capitulo_usuario>();
            this.capitulolibro = new HashSet<capitulolibro>();
            this.concentrado_autores = new HashSet<concentrado_autores>();
            this.libro = new HashSet<libro>();
            this.libro_usuario = new HashSet<libro_usuario>();
            this.proyecto_usuario = new HashSet<proyecto_usuario>();
            this.proyectos = new HashSet<proyectos>();
            this.trabajo = new HashSet<trabajo>();
            this.trabajo_usuario = new HashSet<trabajo_usuario>();
            this.tesis = new HashSet<tesis>();
            this.tesis1 = new HashSet<tesis>();
            this.tesis11 = new HashSet<tesis>();
        }

        public int idUsuario { get; set; }
        public string Nombre { get; set; }
        [DisplayName("Usuario")]
        [Required]
        [RegularExpression(@"^[0-9ña-zÑA-Z''-'\s]{1,40}$", ErrorMessage = "Los caracteres especiales no son permitidos en este campo")]
        [MinLength(5, ErrorMessage = "El usuario debe ser de al menos 5 caracteres")]
        public string Usuario1 { get; set; }
        [Required]
        [RegularExpression(@"^[0-9ña-zÑA-Z''-'\s]{1,40}$", ErrorMessage = "Los caracteres especiales no son permitidos en este campo")]
        [MinLength(5, ErrorMessage = "La contraseña debe ser de al menos 5 caracteres")]
        public string Contraseña { get; set; }
        [Required]
        public string Correo { get; set; }
        [DisplayName("Tipo de Usuario")]
        [Required]
        public Nullable<int> TipoUsuario { get; set; }
        [DisplayName("Apellido Paterno")]
        [Required]
        public string Apellido_Paterno { get; set; }
        [DisplayName("Apellido Materno")]
        [Required]
        public string Apellido_Materno { get; set; }
        public string Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo> articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo_usuario> articulo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<capitulo_usuario> capitulo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<capitulolibro> capitulolibro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concentrado_autores> concentrado_autores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro_usuario> libro_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyecto_usuario> proyecto_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos> proyectos { get; set; }
        public virtual tipousuario tipousuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajo> trabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajo_usuario> trabajo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tesis> tesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tesis> tesis1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tesis> tesis11 { get; set; }
    }
}
